name: Test MATLAB Setup

on:
  push:
    branches: [main]

jobs:

  test:

    name: MATLAB ${{ matrix.matlab }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        matlab: [R2021b, R2022a, R2022b, R2023a, R2023b, latest]

    steps:

      - name: Set up MATLAB with optimization toolbox and parallel computing toolbox
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ matrix.matlab }}
          products: Optimization_Toolbox Parallel_Computing_Toolbox